### ISSUE TITLE
errors with dataset

### ISSUE THREAD

**Issue by guangtugao** [PacificBiosciences/pbcoretools#113]
When I run: 
dataset create --type ConsensusReadSet combined_demux.consensusreadset.xml \
    prefix.5p--barcode1_3p.bam \
    prefix.5p--barcode2_3p.bam \
    prefix.5p--barcode3_3p.bam ...
I got the following error message:
 invalid literal for int() with base 16: '9298aa57/0--1'
Traceback (most recent call last):
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcoretools/dataset.py", line 59, in run
    return args.func(args)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcoretools/DataSetEntryPoints.py", line 62, in createXml
    generateIndices=args.generateIndices)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2018, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 485, in __init__
    self.updateCounts()
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2598, in updateCounts
    self.assertIndexed()
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2428, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1975, in _assertIndexed
    self._openFiles()
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2099, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 374, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 183, in __init__
    self._loadReadGroupInfo()
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 81, in _loadReadGroupInfo
    rgID = rgAsInt(rg["ID"])
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/align/_BamSupport.py", line 58, in rgAsInt
    return np.int32(int(rgIdString, 16))
ValueError: invalid literal for int() with base 16: '9298aa57/0--1'
[ERROR] 2020-07-21 16:35:39,435Z [pbcoretools.dataset _pacbio_main_runner 143] invalid literal for int() with base 16: '9298aa57/0--1'
Traceback (most recent call last):
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcoretools/dataset.py", line 59, in run
    return args.func(args)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcoretools/DataSetEntryPoints.py", line 62, in createXml
    generateIndices=args.generateIndices)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2018, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 485, in __init__
    self.updateCounts()
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2598, in updateCounts
    self.assertIndexed()
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2428, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1975, in _assertIndexed
    self._openFiles()
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2099, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 374, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 183, in __init__
    self._loadReadGroupInfo()
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 81, in _loadReadGroupInfo
    rgID = rgAsInt(rg["ID"])
  File "/home/ggao/miniconda2/lib/python2.7/site-packages/pbcore/io/align/_BamSupport.py", line 58, in rgAsInt
    return np.int32(int(rgIdString, 16))
ValueError: invalid literal for int() with base 16: '9298aa57/0--1'

I would appreciate if someone could help me to figure out what went wrong.

Thanks,
Guangtu

**Comment by guangtugao** [comment]
Looks like this is python version issue.
GT
